version: '3.9'

services:
  fastapi:
    container_name: fastapi
    volumes:
      - .:/code/app
    build:
      context: .
    command: >
        sh -c "uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - 5000:5000

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fastapi


